# Generated by Django 3.2.5 on 2021-07-12 08:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('lab_name', models.CharField(max_length=200)),
                ('hospital_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(default='none', max_length=10)),
                ('contact_number', models.IntegerField()),
                ('pan_number', models.CharField(max_length=10)),
                ('vat_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('services', models.CharField(max_length=200, verbose_name=django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.'))),
                ('location', models.CharField(max_length=50)),
                ('branches', models.IntegerField()),
                ('branLocation', models.CharField(max_length=200, verbose_name=django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.'))),
            ],
        ),
        migrations.CreateModel(
            name='LabImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('image_path', models.CharField(max_length=256)),
                ('img_type', models.CharField(choices=[('profile', 'Profile Picture'), ('pan', 'PAN Card'), ('vat', 'VAT'), ('citizenship', 'Citizenship Card'), ('license', 'License')], default='license', max_length=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
            ],
        ),
    ]
